#+TITLE: About Me
#+DATE: 2023-10-22T01:43:48+09:00
#+PUBLISHDATE: 2023-10-22T01:43:48+09:00
#+DRAFT: false


* Who Am I?
Hello, I am Jinho Park from South Korea.

I graduated [[https://www.konkuk.ac.kr/do/Index.do][Konkuk University]] in 2022 with a bachelor's degree in Electrical and Electronics Engineering.

Currently I work as a machine learning engineer.

* What Is This Blog About?
This is where I keep my *study notes*. Please note that *I cannot
guarantee that all the materials you see here are 100% correct*, but I
will do my best to ensure accuracy and provide references when
possible.

* Why Do I Publish My Notes?
The purpose of publishing is to share my knowledge with others, receive feedback, and improve my writing skills.

I believe that communication skills, especially writing skills, are essential for developers.

* Where Can You Find Me?
If you'd like to contact me for any reason, you can find me at the following links:
- [[https://www.linkedin.com/in/jinho-park-9a511a1b9/][linkedin]]
- [[https://github.com/jinhopark8345][github]]
